### ISSUE TITLE
运行依赖缺失

### ISSUE THREAD

**Issue by MCredbear** [linuxdeepin/go-x11-client#10]
golang-github-gavv-monotime这个依赖的源码包仓库已经404了（使用apt source获取这个源码包时提示的地址）

**Comment by MCredbear** [comment]
虽然在github上找到了这个依赖的源码仓库，但是这个东西怎么打包？

**Comment by BLumia** [comment]
cc @electricface

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
